=== Geekid812/TrackmaniaBingo/common/schema/types.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This XML schema definition validates the types.xml file.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="datatypes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="struct" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="enum" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="struct">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" type="string" minOccurs="0" maxOccurs="1" />
                <xs:element ref="m" maxOccurs="unbounded" />
            </xs:sequence>

            <xs:attribute name="name" type="string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="enum">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="comment" type="string" minOccurs="0" maxOccurs="1" />
                <xs:element ref="v" maxOccurs="unbounded" />
            </xs:sequence>

            <xs:attribute name="name" type="string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="m">
        <xs:complexType>
            <xs:attribute name="name" type="string" use="required" />
            <xs:attribute name="type" type="string" use="required" />
            <xs:attribute name="optional" type="xs:boolean" />
        </xs:complexType>
    </xs:element>

    <xs:element name="v">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="string">
                    <xs:attribute name="id" type="xs:integer">
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Geekid812/TrackmaniaBingo/common/types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    This file contains the type definitions for data structures shared between the game
    client and the server.
    
    The `typegen.py` tool uses this file to generate Angelscript
    and Rust bindings of these data types, which are exported to `client/src/datatypes.as`
    and `server/src/datatypes.rs` respectively.
-->
<datatypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema/types.xsd">

    <struct name="PlayerRef">
        <comment>A simple reference to a registered player.</comment>
        <m name="uid" type="uint" />
        <m name="name" type="string" />
    </struct>

    <struct name="PlayerProfile">
        <comment>A player's detailed profile.</comment>
        <m name="uid" type="int" />
        <m name="name" type="string" />
        <m name="account_id" type="string" />
        <m name="created_at" type="datetime" />
        <m name="last_played_at" type="datetime" />
        <m name="country_code" type="string" />
        <m name="title" type="string" optional="true" />
        <m name="games_played" type="uint" />
        <m name="games_won" type="uint" />
    </struct>

    <struct name="RoomConfiguration">
        <comment>Room parameters set by the host.</comment>
        <m name="name" type="string" />
        <m name="public" type="bool" />
        <m name="randomize" type="bool" />
        <m name="size" type="uint" />
        <m name="host_control" type="bool" />
    </struct>

    <struct name="MatchConfiguration">
        <comment>Match parameters set by the host.</comment>
        <m name="game" type="GamePlatform" default="GamePlatform::Next" />
        <m name="mode" type="Gamemode" default="Gamemode::Standard" />
        <m name="grid_size" type="uint" default="5" />
        <m name="selection" type="MapMode" default="MapMode::RandomTMX" />
        <m name="target_medal" type="Medal" default="Medal::Author" />
        <m name="discovery" type="bool" default="false" />
        <m name="secret" type="bool" default="false" />
        <m name="time_limit" type="duration" />
        <m name="no_bingo_duration" type="duration" />
        <m name="overtime" type="bool" default="true" />
        <m name="late_join" type="bool" default="true" />
        <m name="rerolls" type="bool" default="true" />
        <m name="competitve_patch" type="bool" />
        <m name="mappack_id" type="uint" optional="true" />
        <m name="campaign_selection" type="list[uint]" optional="true" />
        <m name="map_tag" type="int" optional="true" default="3" />
        <m name="items" type="FrenzyItemSettings" />
        <m name="items_expire" type="uint" default="600" />
        <m name="items_tick_multiplier" type="uint" default="1000" />
        <m name="rally_length" type="uint" default="600" />
        <m name="jail_length" type="uint" default="600" />
    </struct>

    <struct name="FrenzyItemSettings">
        <comment>Item drawing probabilities for configuring the Frenzy gamemode.</comment>
        <m name="row_shift" type="uint" default="3" />
        <m name="column_shift" type="uint" default="3" />
        <m name="rally" type="uint" default="3" />
        <m name="jail" type="uint" default="3" />
        <m name="rainbow" type="uint" default="3" />
        <m name="golden_dice" type="uint" default="3" />
    </struct>

    <struct name="HandshakeRequest">
        <comment>Request to open a connection by the client using an exisiting token.</comment>
        <m name="version" type="string" />
        <m name="game" type="GamePlatform" />
        <m name="token" type="string" />
    </struct>

    <struct name="KeyExchangeRequest">
        <comment>Request to generate a client token with the provided credientials.</comment>
        <m name="key" type="string" />
        <m name="display_name" type="string" />
        <m name="account_id" type="string" />
    </struct>

    <struct name="CampaignMap">
        <comment>A map identifier for an official campaign.</comment>
        <m name="campaign_id" type="int" default="-1" />
        <m name="map" type="int" default="-1" />
    </struct>

    <struct name="ChatMessage">
        <comment>A message sent by a player in a text chat.</comment>
        <m name="uid" type="uint" />
        <m name="name" type="string" />
        <m name="title" type="string" optional="true" />
        <m name="timestamp" type="datetime" />
        <m name="content" type="string" />
        <m name="team_message" type="bool" />
    </struct>

    <struct name="PollChoice">
        <comment>One of the available options in a poll.</comment>
        <m name="text" type="string" />
        <m name="color" type="rgbColor" />
    </struct>

    <struct name="Poll">
        <comment>A set of choices to which players can answer.</comment>
        <m name="id" type="uint" />
        <m name="title" type="string" />
        <m name="color" type="rgbColor" />
        <m name="duration" type="duration" />
        <m name="choices" type="list[PollChoice]" />
    </struct>

    <enum name="GamePlatform">
        <comment>Supported game platforms in Bingo.</comment>
        <v>Next</v>
    </enum>

    <enum name="MapMode">
        <comment>Available map selection modes.</comment>
        <v>RandomTMX</v>
        <v>Tags</v>
        <v>Mappack</v>
        <v>Campaign</v>
    </enum>

    <enum name="Medal">
        <comment>A Trackmania medal ranking.</comment>
        <v>WR</v>
        <v>Author</v>
        <v>Gold</v>
        <v>Silver</v>
        <v>Bronze</v>
        <v>None</v>
    </enum>

    <enum name="Gamemode">
        <comment>A selection of game rules.</comment>
        <v>Standard</v>
        <v>Frenzy</v>
    </enum>

    <enum name="HandshakeFailureIntentCode">
        <comment>When a connection to the server fails, give the client a hint of what it should do.</comment>
        <v>ShowError</v>
        <v>RequireUpdate</v>
        <v>Reauthenticate</v>
    </enum>

    <enum name="Powerup">
        <comment>A powerup from the Frenzy gamemode.</comment>
        <v>Empty</v>
        <v>RowShift</v>
        <v>ColumnShift</v>
        <v>Rally</v>
        <v>Jail</v>
        <v>RainbowTile</v>
        <v>GoldenDice</v>
    </enum>
</datatypes>
